### ISSUE TITLE
Pod IP address assignment slow/stuck

### ISSUE THREAD

**Issue by fernandesnikhil** [aws/amazon-vpc-resource-controller-k8s#124]
**Describe the Bug**:
Pods using the Security Groups for pods feature remain stuck in the `ContainerCreating` status waiting for an IP address to be assigned. We notice the pods do not have an IP address assigned and the most recent event on the pod is like the following:
```
Warning  FailedCreatePodSandBox  6s (x175 over 38m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "928809399f9e9384f0a1f97c7dace19e9ee3e33596428695fa6dda205a987bd0": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
```

**Observed Behavior**:
Pods using the Security Groups for pods feature are stuck waiting in excess of 10 mintues for IP address assignment.

**Expected Behavior**:
Pods using the Security Groups for pods feature are assigned IP addresses quickly (not sure what's the EKS SLA here, I assume in a minute or two?)

**How to reproduce it (as minimally and precisely as possible)**:
Unknown

**Additional Context**:
We have had several instances of this happening on a single EKS cluster. In the worst case it we have noted pods waiting over 100 minutes for an IP address. We never see these pods receive an IP address. We keep deleting these stuck pods until we find the newly created pods have an IP address assigned within a few minutes after the pod has been created. These incidents where the VPC resource controller appears to be unable to assign pod IPs for pods using the Security Groups for pods feature seem to happen sporadically and eventually recovers on it's own.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-eks-84b4fe6", GitCommit:"e1318dce57b3e319a2e3fecf343677d1c4d4aa75", GitTreeState:"clean", BuildDate:"2022-06-09T18:22:07Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- CNI Version: `v1.11.0`
`aws-vpc-cni` helm chart version: `1.1.16`

- OS (Linux/Windows): Linux

**Comment by fernandesnikhil** [comment]
Thanks for making the transfer - makes sense since this seems to have something to do with only pods using the Security Group ofr pods feature.

**Comment by haouc** [comment]
This issue could be related to #122 and #104. We are working on trying out solutions to these issues.

**Comment by barryrobison** [comment]
It appears the linked issues have fixes merged - any hints when we might see this issue resolved in EKS? Thanks!

**Comment by haouc** [comment]
@barryrobison EKS is currently doing a clusters upgrade which includes this controller's latest version. You should expect your clusters be upgraded by the end of next week. If you want us to check the specific cluster(s), please let us know. Thanks.

**Comment by haouc** [comment]
Since we have released several versions so far every one of which has taken some efforts to improve the controller's availability, @barryrobison and @fernandesnikhil are you still seeing this happening in your clusters?

**Comment by sushrk** [comment]
Closing old issue, fixes referenced in above comments are released now. 
Please re-open if needed.

**Comment by mikkoc** [comment]
Hi there, we are still seeing very slow pods IP assignment (we use SG for Pods almost everywhere), sometimes it can take 1-3 minutes for assignment, which is unacceptable for us in order to handle spikes of traffic, or during deployments.

EKS version 1.29
Case ID: 171052468601240

Should I open a new issue here?

**Comment by sushrk** [comment]
Hi @mikkoc, what is the scale of the pods using SGP? 

We expect a small delay in creation of SGP pods when compared to non-SGP pods as each pod requires a branch network interface(ENI); and hence an EC2 API call to create a branch ENI and another EC2 API call to associate the branch and trunk ENI, and the EC2 API calls are the major cause for the delay in pod creation.

**Comment by mikkoc** [comment]
@sushrk We're seeing delays of up to 2-2.5 mins. The scale is about 150-200 pods.

**Comment by easimon** [comment]
Coworker of @mikkoc here. We have a few clusters (of slightly different sizes) but this is one example:
Since we're (trying to) use auto-scaling on both cluster (karpenter) and deployments, so these numbers are not exact.

- ~ 20 Worker nodes, m7i-flex.2xlarge
- ~ 300 pods total (incl. aws-node etc.), ~250 of which are using one or more security groups
- Our deployment scheme does a rolling update of ~ 170 pods in about 50 deployments "at once", and many of those spend 1-3 minutes waiting for their network interface. 

The events on one of these pods look like these (addresses and IDs redacted). I picked that more or less randomly, and it took 2 minutes to start.

Not sure if that matters, but it logs `SecurityGroupRequested` multiple times, and with different orders of the security group ids (redacted as aaaaa, bbbbb).

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               2m18s                default-scheduler        Successfully assigned NAMESPACE/PODNAME to ip-1-2-3-4.eu-central-1.compute.internal
  Warning  FailedCreatePodSandBox  2m18s                kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "180bd629ca8a...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  2m3s                 kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8bcd43ae10c8...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  108s                 kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4506fd001496...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  93s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "26a3e670cc36...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  82s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8f9394272392...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Normal   SecurityGroupRequested  78s (x2 over 2m18s)  vpc-resource-controller  Pod will get the following Security Groups [sg-aaaa sg-bbbb]
  Warning  FailedCreatePodSandBox  67s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f75bdf77e12b...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  53s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8fbdd2e59c81...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  38s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5203e3476ed0...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  26s                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "010f44292c73...": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Normal   SecurityGroupRequested  18s (x2 over 2m18s)  vpc-resource-controller  Pod will get the following Security Groups [sg-bbbb sg-aaaa]
  Normal   ResourceAllocated       17s                  vpc-resource-controller  Allocated [{"eniId":"eni-REDACTED","ifAddress":"aa:bb:cc:dd:ee:ff","privateIp":"1.2.3.4","ipv6Addr":"","vlanId":10,"subnetCidr":"1.2.3.4/18","subnetV6Cidr":""}] to the pod
  Normal   Pulled                  17s                  kubelet                  Container image "REDACTED/SOMESERVICE:TAG" already present on machine
  Normal   Created                 17s                  kubelet                  Created container service
  Normal   Started                 17s                  kubelet                  Started container service
```

**Comment by mikkoc** [comment]
@sushrk should we open a new ticket about this? This is becoming a very pressing problem as our ability to handle spikes is hindered. We have already escalated with our TAM.

**Comment by barryrobison** [comment]
@mikkoc we had the same issue and escalated it over two years ago. I wouldn't hold my breath.  Using SGs per pod simply means you can't scale to large pod counts on EKS, and you have to use a different solution.

**Comment by mikkoc** [comment]
@barryrobison did you overcome the issue? how?

@sushrk is this an API rate limiting issue? Can we simply request an increase?

**Comment by easimon** [comment]
Not completely sure, but the events from above show node assignment and first failure to assign an IP address to the pod at the same second, so no matter how long it took to boot the node (or if that node existed already), the pod was stuck 2 mins waiting for an IP address after the node was already there.

**Comment by sushrk** [comment]
Could you please open a AWS support ticket with cluster details so we can take a look?

I haven't observed a delay of 2mins with launching ~250 pods before. Please also share the node type and other relevant information on the ticket.

**Comment by easimon** [comment]
@sushrk I opened the ticket, 171741572300432. Added the node type, cluster size from my comment from above. Let me know if you need more details.

**Comment by easimon** [comment]
@sushrk I also opened a similar ticket in 171820391300199, which is running in a different AWS account, where I can better cut off the cluster from other deployment activity while testing. 

I tried to create a constant environment (no other deployment action, node-pool pre-scaled and fixated to have enough capacity to host both terminating and recreated versions of the deployment pods), waited multiple minutes to "settle" before continuing with the test.

I then ran a script (attached in that support ticket), which, for every 2 seconds, constantly deletes the oldest pod of a 50-pod-deployment. And while IP address assignment (i.e. network interface creation) takes ~ one second *initially*, running this script for 150 seconds (or 75 pods deleted) was enough to collect over 25 pods waiting for IP address assignment, some of which for minutes.

Not all pods suffer the same when this happens. A few of still initialize immediately, others then wait 3 minutes or more for an IP address -- the longer you execute this, the more pods pile up and the longer the delays. Those who wait, seem to wait for N **full** minutes (1 minute or 2 or 3 or 4, but not e.g. 2:37).

**Comment by easimon** [comment]
That being said -- if node autoscaling (via karpenter) is activated, and new nodes need to be created to host the new pods, this gets even worse (and faster so). Nodes are consistently there and "ready" within 15-30 seconds, but scheduled pods sit there multiple minutes without an IP address.

**Comment by fernandesnikhil** [comment]
Given the comments that started coming in here, I felt it might be helpful sharing that we're experiencing the same problems as we had from when we filed this ticket. We have implemented our own instrumentation to measure IP assignment latency. It goes as high as 2000 seconds in really bad scenarios (when we scale up very high). We found that some of our workloads were constantly adding and removing pods to the order of hundreds and they all used Security Groups for Pods and the controller was not able to keep up with the load. The 95th percentile IP assignment latency was most of the time greater than 6 minutes in some of our EKS clusters.
